[config]
schemaVersion = "0.0.1"


[general]
repository = "https://thunderstore.io"


[package]
namespace = "Lordfirespeed"
name = "Refuge_Company"
description = "The Refuge's Lethal Company modpack!"
websiteUrl = "https://github.com/Lordfirespeed/RefugeCompany"
containsNsfwContent = false

[package.dependencies]

# Asset replacers
x753-More_Suits = "1.4.1"
femboytv-LethalPosters = "1.2.0"
Steven-Custom_Boombox_Music = "1.4.0"
Lordfirespeed-Configured_Youtube_Boombox = "0.1.1"

# Asset replacement providers
AlexCodesGames-AdditionalSuits = "1.1.3"
atg-FreeJester = "1.0.3"

# QoL / Bugfixes
notnotnotswipez-MoreCompany = "1.7.2"
FlipMods-HotbarPlus = "1.4.4"
Renegades-WalkieUse = "1.4.0"
Renegades-FlashlightToggle = "1.5.0"
Suskitech-AlwaysHearActiveWalkies = "1.4.3"
Giltong-LethalCompanyDRP = "1.3.6"
tinyhoot-ShipLoot = "1.0.0"
Drakorle-MoreItems = "1.0.1"
ATK-ShipClock = "0.9.0"
SirTyler-BetterTeleporter = "1.2.2"
5Bit-FPSSpectate = "1.0.1"
Mom_Llama-Lethal_Company_Enhancer = "0.1.10"
FutureSavior-Boombox_Sync_Fix = "1.1.2"
Verity-TooManySuits = "1.0.4"
CapyCat-Solos_Bodycams = "1.0.4"
FlipMods-ObjectVolumeController = "1.0.3"

# Features
x753-Mimics = "2.3.0"
FlipMods-TooManyEmotes = "1.5.9"
malco-Lategame_Upgrades = "2.8.5"
Evaisa-LethalThings = "0.8.8"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "assets/configured-youtube-boombox-tracks.json"
target = "/"

[[build.copy]]
source = "assets/config"
target = "/BepInEx/config/"


[publish]
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "modpacks", ]
