[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lordfirespeed"
name = "Refuge_Company"
description = "The Refuge's Lethal Company modpack!"
websiteUrl = "https://github.com/Lordfirespeed/RefugeCompany"
containsNsfwContent = false

[package.dependencies]
### Libraries / dependencies
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.13.0"
2018-LC_API = "3.3.2"
Rune580-LethalCompany_InputUtils = "0.5.5"
Lordfirespeed-YoutubeDLSharp = "1.1.0"
Evaisa-HookGenPatcher = "0.0.5"
IAmBatby-LethalLevelLoader = "1.0.6"
NotAtomicBomb-TerminalApi = "1.5.0"

### Asset replacers
x753-More_Suits = "1.4.1"
femboytv-LethalPosters = "1.2.0"
Steven-Custom_Boombox_Music = "1.4.0"
Lordfirespeed-Configured_Youtube_Boombox = "0.3.1"

### Asset replacement providers
atg-FreeJester = "1.0.3"
TeamClark-SCP_Foundation_Suit = "1.0.1"
Norman-GlowStickSuits = "1.0.4"
ManiaBania-1000_Quota_Stare = "1.0.0"
TeamClark-ODST_Suit = "1.0.0"
Regretti-ClassicDoomguy = "1.0.0"

# Optimizers/Fixes
BlueAmulet-LogNeuter = "1.0.3"
MassiveNewCoilers-FixCentipedeLag = "2023.12.7"
linkoid-DissonanceLagFix = "1.0.0"
FutureSavior-Boombox_Sync_Fix = "1.1.2"

### Quality of Life
notnotnotswipez-MoreCompany = "1.7.4"
FlipMods-HotbarPlus = "1.5.4"
Renegades-WalkieUse = "1.4.0"
Renegades-FlashlightToggle = "1.5.0"
Suskitech-AlwaysHearActiveWalkies = "1.4.4"
Giltong-LethalCompanyDRP = "1.3.6"
tinyhoot-ShipLoot = "1.0.0"
Drakorle-MoreItems = "1.0.2"
SirTyler-BetterTeleporter = "1.2.2"
5Bit-FPSSpectate = "1.0.1"
Verity-TooManySuits = "1.0.5"
CapyCat-Solos_Bodycams = "1.0.5"
FlipMods-ObjectVolumeController = "1.0.4"
Jamil-Corporate_Restructure = "1.0.6"
NotAtomicBomb-Terminal_History = "1.0.4"
Spyci-CozyImprovements = "1.2.1"
Lordfirespeed-Augmented_Enhancer = "0.6.0"

### Features
x753-Mimics = "2.3.2"
Sligili-More_Emotes ="1.3.3"
malco-Lategame_Upgrades = "3.0.1"
Evaisa-LethalThings = "0.9.4"
IntegrityChaos-Diversity = "1.1.10"
scoopy-Scoopys_Variety_Mod = "0.6.5"
KayNetsua-E_Gypt_Moon = "2.0.4"
Jordo-NeedyCats = "1.1.1"
Badham_Mods-SCPFoundationDungeon = "1.5.0"
NomnomAB-RollingGiant = "2.3.0"
Kittenji-Dont_Touch_Me = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "assets/config"
target = "/BepInEx/config/"

[[build.copy]]
source = "assets/plugins"
target = "/BepInEx/plugins/"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "modpacks", ]
